image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
 GIT_DEPTH: 10
 GIT_SSL_NO_VERIFY: "true"

stages:
 - build
 - test
 - deploy
 
job_build:
 stage: build
 tags:
  - docker-runner
 script:
  - dotnet build
 
job_test:
 stage: test
 tags:
  - docker-runner
 script:
  - dotnet test
  
job_deploy:
 stage: deploy
 tags:
  - docker-runner 
 only:
  - master
 artifacts:
  paths:
   - publish/
 script:
  - dotnet publish -c Release -o ./publish TasksOnlineWebAPI/TasksOnlineWebAPI.csproj